# Generated by Django 5.2.12 on 2026-04-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('transcript', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=0)),
                ('target_words', models.IntegerField(default=150)),
                ('faithfulness', models.FloatField(default=0.0)),
                ('transcript_file', models.CharField(blank=True, default='', max_length=500)),
                ('summary_file', models.CharField(blank=True, default='', max_length=500)),
                ('audio_file', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
